### PR TITLE
Antialiasing

### PR DESCRIPTION
**Pull request by GreenToad**
Hi

Tinkered a bit around source code and added optional antialiasing and bilinear interpolation. Tried to do it with as little modifications as possible and without reorganizing anything. Obviously there is a performance impact when enabled. There are some more places that could be antialiased/filtered but most of drawing is antialiased/interpolated. 

Added additional hints in "setFontHints" so that begs refactoring to "setRenderingConfig" or something like that but decided to leave it to you if you decide to merge it.

### CODE REVIEW

**Comment by rayfowler** [comment]
I need to be convinced that this change is necessary

**Comment by GreenToad** [comment]
It absolutelly is not necesarry, that's why i added it as an option that is off by default, take a look how it looks
rotp_antialiasing

**Comment by rayfowler** [comment]
ok, awesome. Let me think about how I want to incorporate these changes.

**Comment by rayfowler** [comment]
Merging, but will be changing the way preferences are set on the Game UI

**Pull request merged**
